### ISSUE TITLE
Works but where is the time setting?

### ISSUE THREAD

**Issue by kylewelsby** [elandesign/formtastic_calendar#1]
I love the plugin, just what I need. but where can I add the Time.

Cheers

**Comment by elandesign** [comment]
Hi Kyle,

There's is no time input primarily because the original JS date picker didn't have one, and I didn't need one for the project I was working on. 

I'll put it on the wishlist as it would be useful, but I'm bogged down with deadlines at the minute so it could be a while before I can come up with anything.

Paul

**Comment by kylewelsby** [comment]
Closing stale issue
